import { RecipeData } from "./Types/recipe";

export const ratingOptions = [0, 3, 3.5, 4, 4.5];
export const typeOptions = ['', 'gelato', 'ice cream', 'sorbet'];
const recipes
   : RecipeData[] = [
      {
         id: "2",
         recipeName: "nice cream 1",
         user: { id: "1", userName: "User 1" },
         specialMarks: {
           lowSugar: false,
           highSugar: true,
           subSugar: false,
           lowFat: false,
           highFat: true,
           vegan: false,
           withEggs: true,
         },
         recipeRating: {
           likes: 10,
           ratingValue: 4.5,
           ratingAmount: 20,
         },
         recipeIngredient: {
           ingredients: [
             [
               {
                 id: "1",
                 name: "Milk",
                 category: "dairy",
                 calories: 42,
                 fat: 2,
                 proteins: 3.4,
                 solids_percentage: 12.5,
                 otherSolids: 9.5,
                 msnf: 8.5,
               },
               500,
             ],
             [
               {
                 id: "2",
                 name: "Sugar",
                 category: "sugars",
                 calories: 387,
                 fat: 0,
                 proteins: 0,
                 solids_percentage: 100,
                 otherSolids: 100,
                 msnf: 0,
               },
               200,
             ],
           ],
           kind: "ice cream",
           totalWeight: 700,
           butterFat: 10,
           msnf: 20,
           pac: 30,
           pod: 40,
           totalSolid: 50,
         },
       },
       {
        id: "21",
        recipeName: "Strawberry Cheesecake Ice Cream",
        user: { id: "5", userName: "User 5" },
        specialMarks: {
          lowSugar: false,
          highSugar: true,
          subSugar: false,
          lowFat: false,
          highFat: true,
          vegan: false,
          withEggs: true,
        },
        recipeRating: {
          likes: 40,
          ratingValue: 4.8,
          ratingAmount: 50,
        },
        recipeIngredient: {
          ingredients: [
            [
              {
                id: "11",
                name: "Cream Cheese",
                category: "dairy",
                calories: 342,
                fat: 33,
                proteins: 6,
                solids_percentage: 50,
                otherSolids: 25,
                msnf: 25,
              },
              200,
            ],
            [
              {
                id: "12",
                name: "Strawberries",
                category: "fruits",
                calories: 45,
                fat: 0.4,
                proteins: 0.9,
                solids_percentage: 95,
                otherSolids: 2,
                msnf: 3,
              },
              150,
            ],
          ],
          kind: "ice cream",
          totalWeight: 350,
          butterFat: 15,
          msnf: 28,
          pac: 20,
          pod: 25,
          totalSolid: 30,
        },
      },
    
      // Recipe 22
      {
        id: "22",
        recipeName: "Cookies and Cream Ice Cream",
        user: { id: "6", userName: "User 6" },
        specialMarks: {
          lowSugar: false,
          highSugar: true,
          subSugar: false,
          lowFat: false,
          highFat: true,
          vegan: false,
          withEggs: true,
        },
        recipeRating: {
          likes: 35,
          ratingValue: 4.7,
          ratingAmount: 45,
        },
        recipeIngredient: {
          ingredients: [
            [
              {
                id: "13",
                name: "Chocolate Cookies",
                category: 'adding',
                calories: 502,
                fat: 23,
                proteins: 5,
                solids_percentage: 85,
                otherSolids: 15,
                msnf: 10,
              },
              150,
            ],
            [
              {
                id: "14",
                name: "Vanilla Extract",
                category: 'adding',
                calories: 288,
                fat: 0,
                proteins: 0,
                solids_percentage: 10,
                otherSolids: 10,
                msnf: 0,
              },
              10,
            ],
          ],
          kind: "ice cream",
          totalWeight: 160,
          butterFat: 8,
          msnf: 15,
          pac: 20,
          pod: 25,
          totalSolid: 30,
        },
      },
      {
        id: "23",
        recipeName: "Pistachio Gelato",
        user: { id: "7", userName: "User 7" },
        specialMarks: {
          lowSugar: false,
          highSugar: true,
          subSugar: false,
          lowFat: false,
          highFat: true,
          vegan: false,
          withEggs: true,
        },
        recipeRating: {
          likes: 30,
          ratingValue: 1.6,
          ratingAmount: 40,
        },
        recipeIngredient: {
          ingredients: [
            [
              {
                id: "15",
                name: "Pistachio Nuts",
                category: "nuts",
                calories: 562,
                fat: 45,
                proteins: 20,
                solids_percentage: 95,
                otherSolids: 5,
                msnf: 15,
              },
              200,
            ],
            [
              {
                id: "16",
                name: "Heavy Cream",
                category: "dairy",
                calories: 340,
                fat: 37,
                proteins: 2.1,
                solids_percentage: 40,
                otherSolids: 10,
                msnf: 30,
              },
              300,
            ],
          ],
          kind: "gelato",
          totalWeight: 500,
          butterFat: 20,
          msnf: 45,
          pac: 20,
          pod: 25,
          totalSolid: 30,
        },
      },
    
      // Recipe 24
      {
        id: "24",
        recipeName: "Dark Chocolate Gelato",
        user: { id: "8", userName: "User 8" },
        specialMarks: {
          lowSugar: false,
          highSugar: true,
          subSugar: false,
          lowFat: false,
          highFat: true,
          vegan: false,
          withEggs: true,
        },
        recipeRating: {
          likes: 25,
          ratingValue: 4.5,
          ratingAmount: 35,
        },
        recipeIngredient: {
          ingredients: [
            [
              {
                id: "17",
                name: "Dark Chocolate",
                category: "adding",
                calories: 546,
                fat: 31,
                proteins: 5.5,
                solids_percentage: 99,
                otherSolids: 1,
                msnf: 10,
              },
              200,
            ],
            [
              {
                id: "18",
                name: "Whole Milk",
                category: "dairy",
                calories: 61,
                fat: 3.3,
                proteins: 3.4,
                solids_percentage: 10,
                otherSolids: 10,
                msnf: 0,
              },
              300,
            ],
          ],
          kind: "gelato",
          totalWeight: 500,
          butterFat: 20,
          msnf: 10,
          pac: 20,
          pod: 25,
          totalSolid: 30,
        },
      },
      {
        id: "26",
        recipeName: "Strawberry Sorbet",
        user: { id: "10", userName: "User 10" },
        specialMarks: {
          lowSugar: false,
          highSugar: true,
          subSugar: false,
          lowFat: true,
          highFat: false,
          vegan: true,
          withEggs: false,
        },
        recipeRating: {
          likes: 15,
          ratingValue: 4.2,
          ratingAmount: 25,
        },
        recipeIngredient: {
          ingredients: [
            [
              {
                id: "20",
                name: "Strawberries",
                category: "fruits",
                calories: 32,
                fat: 0.3,
                proteins: 0.7,
                solids_percentage: 7,
                otherSolids: 7,
                msnf: 0,
              },
              300,
            ],
            [
              {
                id: "21",
                name: "Water",
                category: 'dairy',
                calories: 0,
                fat: 0,
                proteins: 0,
                solids_percentage: 0,
                otherSolids: 0,
                msnf: 0,
              },
              200,
            ],
            [
              {
                id: "22",
                name: "Sugar",
                category: "sugars",
                calories: 387,
                fat: 0,
                proteins: 0,
                solids_percentage: 100,
                otherSolids: 100,
                msnf: 0,
              },
              150,
            ],
          ],
          kind: "sorbet",
          totalWeight: 650,
          butterFat: 0,
          msnf: 0,
          pac: 0,
          pod: 0,
          totalSolid: 0,
        },
      },
    
      // Recipe 27
      {
        id: "27",
        recipeName: "Mango Sorbet",
        user: { id: "11", userName: "User 11" },
        specialMarks: {
          lowSugar: false,
          highSugar: true,
          subSugar: false,
          lowFat: true,
          highFat: false,
          vegan: true,
          withEggs: false,
        },
        recipeRating: {
          likes: 20,
          ratingValue: 4.4,
          ratingAmount: 30,
        },
        recipeIngredient: {
          ingredients: [
            [
              {
                id: "23",
                name: "Mango",
                category: "fruits",
                calories: 60,
                fat: 0.4,
                proteins: 0.6,
                solids_percentage: 15,
                otherSolids: 15,
                msnf: 0,
              },
              400,
            ],
            [
              {
                id: "24",
                name: "Water",
                category: 'dairy',
                calories: 0,
                fat: 0,
                proteins: 0,
                solids_percentage: 0,
                otherSolids: 0,
                msnf: 0,
              },
              200,
            ],
            [
              {
                id: "25",
                name: "Sugar",
                category: "sugars",
                calories: 387,
                fat: 0,
                proteins: 0,
                solids_percentage: 100,
                otherSolids: 100,
                msnf: 0,
              },
              150,
            ],
          ],
          kind: "sorbet",
          totalWeight: 750,
          butterFat: 0,
          msnf: 0,
          pac: 0,
          pod: 0,
          totalSolid: 0,
        },
      },    
    ];
 
 export default recipes;
 